### ISSUE TITLE
do not check in IDE specific files

### ISSUE THREAD

**Issue by theborakompanioni** [perseacado/aquasketch#7]
idea/
*.iml

**Comment by perseacado** [comment]
gitignore.io creates a `.gitignore` file according to https://intellij-support.jetbrains.com/hc/en-us/articles/206544839 and https://github.com/joeblau/gitignore.io/issues/186#issuecomment-215987721). 
maybe I'll remove the `idea/` and `*.iml` files since modern IDEs should be able to import a Maven project anyway.
